version: '3.2'
services:
  mongo:
    image: mongo
    command: mongod
    ports:
      - '27017:27017'
    volumes:
      - "${PROJECT_PATH}/tmp/db:/data/db"
  web:
    build: "${METAL_HOME}/rails"
    command: 'rails server'
    tty: true
    stdin_open: true
    environment:
      BUNDLE_APP_CONFIG: /app/.bundle
    ports:
      - '3000:3000'
    volumes:
      - type: bind
        source: "${PROJECT_PATH}"
        target: /app
    depends_on:
      - mongo
