version: '3.2'
services:
  mongo:
    image: mongo
    command: mongod
    ports:
      - '27017:27017'
  web:
    build:
      context: "${PROJECT_PATH}"
      dockerfile: "${METAL_HOME}/rails/Dockerfile"
    volumes:
      - type: bind
        source: "${PROJECT_PATH}"
        target: /app
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    command: bin/rails server
