version: '3.2'
services:
  mongo:
    image: mongo
    command: mongod
    ports:
      - '27017:27017'
    volumes:
      - '[HOME_PATH]/mongo/db:/data/db'
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    command: mysqld
    ports:
      - '3306:3306'
    volumes:
      - '[HOME_PATH]/mysql/db:/var/lib/mysql'
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - '[HOME_PATH]/nginx/sites:/etc/nginx/conf.d'
    networks:
      default:
        aliases:
          [ALIASES]
  rails:
    build: '[INSTALLATION_PATH]/docker/rails'
  laravel:
    build: '[INSTALLATION_PATH]/docker/laravel'
