  [PROJECT_NAME]:
    build: '[INSTALLATION_PATH]/docker/rails'
    command: 'bin/rails server --binding=0.0.0.0 --port=8000'
    tty: true
    stdin_open: true
    environment:
      BUNDLE_APP_CONFIG: /app/.bundle
    volumes:
      - type: bind
        source: '[PROJECT_PATH]'
        target: /app
    depends_on:
      - mongo
      - mysql
