version: '3.2'
services:
  mongo:
    image: mongo
    command: mongod
    ports:
      - '27017:27017'
    volumes:
      - "[HOME_PATH]/mongo/db:/data/db"
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
    volumes:
      - "[HOME_PATH]/nginx/sites:/etc/nginx/conf.d"
    networks:
      default:
        aliases:
          [ALIASES]
  rails:
    build: "[INSTALLATION_PATH]/docker/rails"
